force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <displayFormat>S{000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Beds_Amount__c.field-meta.xml
<CustomField>
    <fullName>Beds_Amount__c</fullName>
    <label>Beds Amount</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Beds_Taken__c.field-meta.xml
<CustomField>
    <fullName>Beds_Taken__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Beds Taken</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Free_Beds__c.field-meta.xml
<CustomField>
    <fullName>Free_Beds__c</fullName>
    <formula>Beds_Amount__c -  Beds_Taken__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Free Beds</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single room</fullName>
            </value>
            <value>
                <fullName>Multibed room</fullName>
            </value>
            <value>
                <fullName>Operating Room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/recordTypes/Ward_Room.recordType-meta.xml
<RecordType>
    <fullName>Ward_Room</fullName>
    <active>true</active>
    <label>Ward Room</label>
</RecordType>

force-app/main/default/classes/Room_CTRL.cls
public with sharing class Room_CTRL {
    private final static RecordType WARD_ROOM = [SELECT Id FROM RecordType WHERE Name = 'Ward Room' LIMIT 1];

    @AuraEnabled
    public static List<Room__c> getAllRooms(){
        return[
            SELECT Id, Name, Free_Beds__c, Beds_Amount__c, Type__c FROM Room__c WHERE RecordTypeId = :WARD_ROOM.Id ORDER BY Name
        ];
    }

    @AuraEnabled
    public static Id getRoomIdFromName(string name){
        Room__c room = [
            SELECT Id FROM Room__c WHERE Name = :name AND Free_Beds__c > 0 LIMIT 1
        ];
        return room.Id;
    }

    @AuraEnabled
    public static void assignBed(String roomId){
            Room__c room = [SELECT Free_Beds__c, Beds_Taken__c FROM Room__c WHERE Id = :roomId];
            if(room.Free_Beds__c > 0){
                room.Beds_Taken__c += 1;
                update room; 
            } else{
                throw new AuraHandledException('This room has no free beds');
            }
    }
}