force-app/main/default/objects/Labor__c/Labor__c.object-meta.xml
<CustomObject>
    <label>Labor</label>
    <nameField>
        <displayFormat>L{00000}</displayFormat>
        <label>Labor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Labors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Labor__c/fields/Birth_Time__c.field-meta.xml
<CustomField>
    <fullName>Birth_Time__c</fullName>
    <description>Date and time of the labor end</description>
    <label>Birth Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause of CSection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Not Planned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Labor__c.field-meta.xml
<CustomField>
    <fullName>Labor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Labor</label>
    <referenceTo>Labor__c</referenceTo>
    <relationshipLabel>Labors</relationshipLabel>
    <relationshipName>Labors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Labor__c/fields/Pregnancy__c.field-meta.xml
<CustomField>
    <fullName>Pregnancy__c</fullName>
    <label>Pregnancy</label>
    <referenceTo>Pregnancy__c</referenceTo>
    <relationshipLabel>Labors</relationshipLabel>
    <relationshipName>Labors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Labor__c/recordTypes/CSection.recordType-meta.xml
<RecordType>
    <fullName>CSection</fullName>
    <active>true</active>
    <label>CSection</label>
</RecordType>

force-app/main/default/objects/Labor__c/recordTypes/NaturalLabor.recordType-meta.xml
<RecordType>
    <fullName>NaturalLabor</fullName>
    <active>true</active>
    <label>NaturalLabor</label>
</RecordType>

force-app/main/default/objects/Pregnancy__c/Pregnancy__c.object-meta.xml
<CustomObject>
    <label>Pregnancy</label>
    <nameField>
        <label>Pregnancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pregnancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Labor_CTRL.cls
public with sharing class Labor_CTRL {

    private static final RecordType CSECTION = [SELECT Id FROM RecordType WHERE Name = 'CSection' LIMIT 1];
    private static final RecordType NATURAL = [SELECT Id FROM RecordType WHERE Name = 'NaturalLabor' LIMIT 1];


    @AuraEnabled
    public static void startNaturalLabor(Id pregnancyid) {
        try {
            insert new Labor__c(Start_Time__c = DateTime.now(), Pregnancy__c = pregnancyId, RecordTypeId = NATURAL.Id);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void startCSection(Id pregnancyid, String cause) {
        try {
            insert new Labor__c(Start_Time__c = Datetime.now(), Pregnancy__c = pregnancyid, Cause__c = cause, RecordTypeId = CSECTION.Id);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void finishLabor(Datetime endDate, Id laborId) {
        try {
            Labor__c labor = [SELECT Birth_Time__c FROM Labor__c WHERE Id = :laborId];
            labor.Birth_Time__c = endDate;
            upsert labor;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void finishLabor(Datetime endDate, Id laborId, String comments) {
        try {
            Labor__c labor = [SELECT Birth_Time__c, Comments__c FROM Labor__c WHERE Id = :laborId];
            labor.Birth_Time__c = endDate;
            labor.Comments__c = comments;
            upsert labor;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}