force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Patient Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c &amp; &quot; &quot; &amp; IF(ISBLANK(Middle_Name__c), &quot;&quot;, Middle_Name__c + &quot; &quot;) &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/PESEL__c.field-meta.xml
<CustomField>
    <fullName>PESEL__c</fullName>
    <label>PESEL</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pregnancy__c/Pregnancy__c.object-meta.xml
<CustomObject>
    <label>Pregnancy</label>
    <nameField>
        <label>Pregnancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pregnancies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pregnancy__c/fields/Estimated_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_End_Date__c</fullName>
    <label>Estimated End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pregnancy__c/fields/Estimated_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Start_Date__c</fullName>
    <label>Estimated Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pregnancy__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Pregnancies</relationshipLabel>
    <relationshipName>Pregnancies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pregnancy__c/fields/Pregnancy_Multiplicity__c.field-meta.xml
<CustomField>
    <fullName>Pregnancy_Multiplicity__c</fullName>
    <label>Pregnancy Multiplicity</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Patient_CTRL.cls
public with sharing class Patient_CTRL {
    
    public static boolean registerPatient(){
       return true; 
    }

    @AuraEnabled
    public static List<Patient__c> getAllPatients(){
        return[
            SELECT 
                Id,
                PESEL__c, 
                First_Name__c, 
                Middle_Name__c, 
                Last_Name__c, 
                Full_Name__c,
                Date_of_birth__c, 
                Phone__c
            FROM Patient__c
            ORDER BY Last_Name__c, First_Name__c
        ];
        
    }
    
    @AuraEnabled
    public static void addPregnancy(Id patientId, String name, Date estimatedStartDate, Date estimatedEndDate, Integer multiplicity){
        try {
            Pregnancy__c pregnancy = new Pregnancy__c(
                Patient__c = patientId,
                Name = name,
                Estimated_Start_Date__c = estimatedStartDate,
                Estimated_End_Date__c = estimatedEndDate,
                Pregnancy_Multiplicity__c = multiplicity
            );
            insert pregnancy;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}